name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get the version number
        id: get_version
        run: echo "##[set-output name=version;]$(./payload/msda --version 2>&1)"
      - name: Build the package
        run: ./build.sh
      - name: Upload built package
        uses: actions/upload-artifact@master
        with:
          name: ${{ format('MacSetDefaultApps-v{0}.pkg', steps.get_version.outputs.version) }}
          path: ${{ format('./MacSetDefaultApps-v{0}.pkg', steps.get_version.outputs.version) }}

  release:
    runs-on: macOS-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Get the version number
        id: get_version
        run: echo "##[set-output name=version;]$(./payload/msda --version 2>&1)"
      - name: Download built package
        uses: actions/download-artifact@v1
        with:
          name: ${{ format('MacSetDefaultApps-v{0}.pkg', steps.get_version.outputs.version) }}
          path: '.'
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ format('v{0}', steps.get_version.outputs.version) }}
          release_name: ${{ format('v{0}', steps.get_version.outputs.version) }}
          draft: false
          prerelease: false
      - name: Upload built package to release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ format('./MacSetDefaultApps-v{0}.pkg', steps.get_version.outputs.version) }}
          asset_name: ${{ format('MacSetDefaultApps-v{0}.pkg', steps.get_version.outputs.version) }}
          asset_content_type: application/vnd.apple.installer+xml
