name: Test

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install testing dependencies
        run: pip3 install -r requirements/ci.txt
      - name: Run fake filesystem tests
        run: ./tests/fake_filesystem_tests.py
      - name: Run unit tests
        run: ./tests/tests.py
      - name: Run functional tests
        run: ./tests/functional_tests.py
