#!/usr/bin/python

"""\
Directly modifies launchservices plists to set default file associations in macOS.

A somewhat complete list of UTI's can be found here:
	https://escapetech.eu/manuals/qdrop/uti.html\
"""

from __future__ import print_function

import os, shutil, subprocess, sys
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from plistlib import readPlist, writePlist
from tempfile import NamedTemporaryFile

__author__ = 'David G. Rosenberg'
__copyright__ = 'Copyright (c), Mac Set Default Apps'
__license__ = 'MIT'
__version__ = '1.0.0'
__email__ = 'dgrosenberg@icloud.com'

# Settings
PLIST_NAME = 'com.apple.launchservices.secure.plist'
TMP_PREFIX = 'msda_tmp_'
JAMF = False

# Functions
def process_args(arguments):
	parser = ArgumentParser(
		description=__doc__,
		formatter_class=RawDescriptionHelpFormatter,
		epilog='Please email {} with any issues'.format(
			__email__,
		)
	)
	parser.add_argument(
		'app_id',
		help='the identifier of the application to set as a default',
		type=str,
	)
	parser.add_argument(
		'-p', '--protocol',
		help='protocols to associate with the given app ID',
		action='append',
	)
	parser.add_argument(
		'-u', '--uti',
		help='UTIs and roles to associate with the given app ID',
		action='append',
		nargs=2,
		metavar=('UTI', 'ROLE'),
	)
	parser.add_argument(
		'-v', '--verbose',
		help='verbose output',
		action='store_true',
	)
	parser.add_argument(
		'--version',
		help='display version number',
		action='version',
	)

	return parser.parse_args(arguments)

def _create_plist_parents(plist_path):
	"""
	Creates the directory structure if the provided plist doesn't exist
	"""

	# if the specified plist already exists, don't do anything
	if os.path.isfile(plist_path):
		return False

	# if the specified plist's parent directories already exist, don't do
	# anything
	parent_path = os.path.dirname(plist_path)
	if os.path.exists(parent_path):
		return False

	# create the parent directories for the specified plist
	os.makedirs(parent_path)
	return plist_path


# Classes
class LSHandler(object):

	def _from_dict(self, from_dict):
		"""
		Creates an LSHandler object from a dictionary
		"""

		# grab the role from the string containing it
		self.role = from_dict['LSHandlerPreferredVersions'].keys()[0]
		self.role = self.role[13:].lower()

		# grab the UTI/protocol
		try:
			# for if it's a UTI
			self.uti = from_dict['LSHandlerContentType'].lower()
			self._type = 'ContentType'
		except KeyError:
			# for if it's a protocol
			self.uti = from_dict['LSHandlerURLScheme'].lower()
			self._type = 'URLScheme'

		# grab the App ID
		self.app_id = from_dict[self._role_key].lower()

	def _from_properties(self, **kwargs):
		"""
		Creates an LSHandler from specified properties
		"""
		self.app_id = kwargs['app_id'].lower()
		self.uti = kwargs['uti'].lower()

		# determines if we're working with a UTI or protocol based on the
		# presence of periods
		if '.' in self.uti:
			self._type = 'ContentType'
			self.role = kwargs.get('role', 'all').lower()
		else:
			self._type = 'URLScheme'
			self.role = 'all'

	def __init__(self, from_dict=None, **kwargs):
		if from_dict:
			self._from_dict(from_dict)
		else:
			self._from_properties(**kwargs)

	@property
	def _role_key(self):
		"""
		Generates the dictionary key for an LSHandler's role
		"""
		return 'LSHandlerRole' + self.role.capitalize()

	def __eq__(self, other):
		"""
		Two LSHandlers for the same role and UTI would be considered equal
		"""
		compare_utis = self.uti == other.uti
		if self.role == 'all' or other.role == 'all':
			compare_roles = True
		else:
			compare_roles = self.role == other.role
		return compare_utis and compare_roles

	def __ne__(self, other):
		return not self == other

	def __iter__(self):
		yield ('LSHandler' + self._type, self.uti)
		yield (self._role_key, self.app_id)
		yield ('LSHandlerPreferredVersions', { self._role_key: '-' })


class LaunchServices(object):

	def __init__(self, plist=None):
		self.handlers = []
		self.plist = plist

		if self.plist:
			self.read()

	def __iter__(self):
		yield ('LSHandlers', [ dict(h) for h in self.handlers ])

	def read(self):
		"""
		Reads the plist at the specified path into a LaunchServices object,
		creating LSHandler objects as necesary
		"""

		# is the specified plist doesn't exist, there's nothing to read
		if not os.path.isfile(self.plist):
			return

		with NamedTemporaryFile(prefix=TMP_PREFIX, delete=True) as tmp_plist:
			# copy the target plist to a temporary file
			tmp_path = tmp_plist.name
			shutil.copyfile(self.plist, tmp_path)

			# convert to XML from binary
			convert_command = '/usr/bin/plutil -convert xml1 ' + tmp_path
			subprocess.check_output(convert_command.split())

			# read the plist
			plist = readPlist(tmp_path)

		# convert any specified LSHandlers to objects
		for lshandler in plist['LSHandlers']:
			self.handlers.append(LSHandler(from_dict=lshandler))

	def write(self, plist=None):
		"""
		Writes this object to the specified plist, formatting it as a
		LaunchServices plist
		"""

		# allow for alternate destinations (mostly for testing)
		if not plist:
			plist = self.plist

		# create parents directories if they don't exist
		_create_plist_parents(plist)

		with NamedTemporaryFile(prefix=TMP_PREFIX, delete=True) as tmp_plist:
			# write the LaunchServices object to a temporary file
			tmp_path = tmp_plist.name
			writePlist(dict(self), tmp_path)

			# convert it to binary
			convert_command = '/usr/bin/plutil -convert binary1 ' + tmp_path
			subprocess.check_output(convert_command.split())

			# and overwrite the specified plist
			shutil.copyfile(tmp_path, plist)

	@property
	def app_ids(self):
		"""
		Provides a set of all App IDs set as default handlers
		"""
		collected_app_ids = [ h.app_id for h in self.handlers ]
		return set(collected_app_ids)

	def set_handler(self, **kwargs):
		"""
		Generates a new LSHandler object, replacing any existing LSHandler
		objects that conflict with it
		"""
		new_lshandler = LSHandler(**kwargs)
		self.handlers = [ h for h in self.handlers if h != new_lshandler ]
		self.handlers.append(new_lshandler)
		return new_lshandler


def main(arguments):
	if JAMF:
		args = process_args(arguments[2:])
	else:
		args = process_args(arguments)
	print(args)

if __name__ == '__main__':
	sys.exit(main(sys.argv[1:]))
