name: tests

on: [push]

jobs:
  test:
    permissions:
      checks: write

    strategy:
      matrix:
        os: [macos-12, macos-13, macos-14]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Install dependencies
        run: yarn

      - run: mkdir -p reports

      - name: Run tests
        run: yarn test --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_INCLUDE_CONSOLE_OUTPUT: true
          JEST_JUNIT_OUTPUT_FILE: reports/${{ matrix.os }}.xml

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: ${{ always() }}
        with:
          name: test results (${{ matrix.os }})
          path: reports/${{ matrix.os }}.xml
          reporter: jest-junit
